package channels

import "fmt"

func SimpleChan() {
	stringStream := make(chan string)
	go func() {
		stringStream <- "Hello channels!"
	}()

	fmt.Println(<-stringStream)
}

func SimpleChanConfirm() {
	stringStream := make(chan string)
	go func() {
		stringStream <- "Hello channels!"
	}()

	// The second return value is a way for a read operation to indicate
	// whether the read off the channel was a value generated by a write
	// elsewhere in the process
	salutation, ok := <-stringStream

	fmt.Printf("%v: %v\n", ok, salutation)
}
